version: '3.6'
services:
  yelp-api:
    # uncomment the below volume to mount the cur dir to app in container, so nodemon will work
    volumes:
      - ./:/usr/src/app
    build: .
    image: yelp-api
    container_name:
      yelp-api
    restart: always
    command: "npm run dev"
    ports:
      - "8000:8000"
    networks:
      - yelp-network
    links:
        - db_mysql
        - db_mongo
    depends_on:
        - db_mysql
        - db_mongo
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: db_mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: 3306
      MONGO_HOST: db_mongo
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_PORT: 27017
      SECRET_KEY: ${SECRET_KEY}

  db_mysql:
    image: mysql:5
    container_name: db_mysql
    restart: always
    volumes:
      - db_mysql-data:/var/lib/mysql
      - ./db-init/:/docker-entrypoint-initdb.d
    networks:
      - yelp-network
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  db_mongo:
    image: mongo:latest
    container_name: db_mongo
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${ROOT_PASSWORD}
    volumes:
      - db_mongo-data:/data/db
      - ./db-init/:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017
    networks:
      - yelp-network


volumes:
  db_mysql-data:
  db_mongo-data:

networks:
  yelp-network:
    driver:
      bridge
